repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform Format
        entry: terraform fmt -recursive
        language: system
        files: \.tf$
        pass_filenames: false

      - id: terraform-validate
        name: Terraform Validate
        entry: bash -c 'terraform init -backend=false && terraform validate'
        language: system
        files: \.tf$
        pass_filenames: false
