---
# tfsec configuration for GCP Terraform security scanning

# Minimum severity level for findings (LOW, MEDIUM, HIGH, CRITICAL)
minimum_severity: MEDIUM

# Exclude specific check IDs
exclude:
  - google-storage-bucket-encryption-customer-key # Optional for simple buckets
  - google-storage-no-public-access # We handle this with public_access_prevention

# Include additional checks
include:
  - google-*

# Soft fail - don't fail the build on security issues, just report them
soft_fail: false

# Configure specific rule severity
severity_overrides:
  google-storage-bucket-encryption-customer-key: LOW
  google-compute-no-public-ip: MEDIUM
  google-compute-disk-encryption-customer-key: LOW

# Format configuration
format: json
out: tfsec-report.json

# Custom check configuration
custom_check_dir: .tfsec/custom_checks

# Debug mode
debug: false

# Include passed checks in output
include_passed: false

# Include ignored checks in output  
include_ignored: true

# Stop on first error
stop_on_errors: false

# Configure workspace
workspace: default